apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dailyfix
type: Opaque
stringData:
  DB_HOST: terraform-20260123163637967800000004.c3ig6w8o0dws.ap-south-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: dailyfix
  DB_USER: admin
  DB_PASSWORD: Akash2003
